web_zerodawn:
    image: nginx:latest
    privileged: true
    ports:
        - 8881:80
    volumes_from:
        - php
    volumes:
        - ./env/nginx/zerodawn.conf:/etc/nginx/conf.d/default.conf
        - ./env/nginx/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    links:
        - php

web_tardis:
    image: nginx:latest
    privileged: true
    ports:
        - 8000:8000
    volumes_from:
        - php
    volumes:
        - ./env/nginx/tardis.local.conf:/etc/nginx/conf.d/tardis.conf
    links:
        - php

php:
    build: ./env/php-7
    privileged: true
    links:
        - redis
        - mysql
    environment:
        REDIS_HOST: redis
        REDIS_PORT: 6379
    volumes:
        - ./:/var/www/aloy
        - ../tardis/:/var/www/tardis
        - ./env/nginx/custom.ini:/usr/local/etc/php/conf.d/custom.ini

redis:
    image: redis
    ports:
      - 6379:6379
    mem_limit: 1g

mysql:
    image: mysql:5.7
    ports:
        - 3306:3306
    volumes:
        - db_data:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=mydbroot
        - MYSQL_DATABASE=zerodawn