web_groot:
    image: nginx:latest
    privileged: true
    ports:
        - 80:80
    volumes_from:
        - php
    volumes:
        - ./env/nginx/mm_groot.dev.conf:/etc/nginx/conf.d/default.conf
        - ./env/nginx/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    links:
        - php

web_tardis:
    image: nginx:latest
    privileged: true
    ports:
        - 8000:8000
    volumes_from:
        - php
    volumes:
        - ./env/nginx/tardis.local.conf:/etc/nginx/conf.d/tardis.conf
    links:
        - php

php:
    build: ./env/php-7
    privileged: true
    links:
        - redis
    environment:
        REDIS_HOST: redis
        REDIS_PORT: 6379
    volumes:
        - ./:/var/www/mm_groot
        - ../tardis/:/var/www/tardis
        - ./env/nginx/custom.ini:/usr/local/etc/php/conf.d/custom.ini

redis:
    image: redis
    ports:
      - 6379:6379
    mem_limit: 1g